# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish docs (elrond-sdk-docs)

on:
  push:
    branches: [ master, github-workflows ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout elrond-sdk
      uses: actions/checkout@v2
      with:
        path: elrond-sdk

    - name: Checkout elrond-sdk-docs
      uses: actions/checkout@v2
      with:
        repository: ElrondNetwork/elrond-sdk-docs
        path: elrond-sdk-docs

    - name: Setup NodeJS (for erdjs docs)
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Set up Python (for erdpy docs)
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build docs (erdjs)
      run: |
        cd ${GITHUB_WORKSPACE}/elrond-sdk/erdjs
        npm ci
        VERSION=$(node -p "require('./package.json').version")
        npx typedoc --includeVersion --out "${GITHUB_WORKSPACE}/elrond-sdk-docs/erdjs/latest"
        npx typedoc --includeVersion --out "${GITHUB_WORKSPACE}/elrond-sdk-docs/erdjs/${VERSION}"

    - name: Build docs (erdpy)
      run: |
        python3 -m pip install --upgrade pip
        sudo apt-get install python3-sphinx
        cd ${GITHUB_WORKSPACE}/elrond-sdk
        pip3 install -r requirements.txt
        sphinx-apidoc -o ${GITHUB_WORKSPACE}/elrond-sdk-docs/source ${GITHUB_WORKSPACE}/elrond-sdk/erdpy
        cd ${GITHUB_WORKSPACE}/elrond-sdk-docs/erdpy
        make html

    - name: Commit and push elrond-sdk-docs
      run: |
        cd ${GITHUB_WORKSPACE}/elrond-sdk-docs
        git status
